### ISSUE TITLE
Releasing alpha from `master`?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/github3.py-feedstock#4]
Seems that we are releasing an alpha version from `master`. Is there a particular reason for us to be doing this? Would it be possible to switch to doing stable releases? Could we put the alpha release under some other label so it doesn't get downloaded from `conda-forge` by default?

cc @sigmavirus24

**Comment by sigmavirus24** [comment]
The alpha releases are pretty much what's going to be 1.0. It's just GitHub keeps breaking their API and I keep not having time to deal with it.

**Comment by scopatz** [comment]
It is a little problematic that the alpha version is the only version in conda-forge for some of my packages which depend on github3.py. It would be better if we could also have a stable version too, which still seems to work well enough.

**Comment by sigmavirus24** [comment]
There is a stable version available from the 0.9.x branch. I'm not sure if conda is happy with multiple versions being available.

**Comment by scopatz** [comment]
Conda is happy with multiple version. My comment was more of a request/personal to-do to actually make 0.9.x available

**Comment by CJ-Wright** [comment]
Is there any way for the stable to trump the alpha release?

**Comment by scopatz** [comment]
I think that you just have to pin it in your downstream recipes.

**Comment by jakirkham** [comment]
This appears to be a non-issue now that stable releases are available on `master`. Going to close this out. If we want to add 0.9.x, am totally fine with that. Also ok with just using 1.0 too. Feel free to keep discussing as needed.

**Comment by scopatz** [comment]
Just as a point of reference, we did add 0.9.6, I believe
